version: '3'

tasks:
  build:
    desc: Build the production bin
    cmds:
      - wails build -ldflags="-s -w"

  dev:
    desc: Run wails in development 
    cmds:
      - wails dev
  
  clean:
    desc: Removes the dist folder
    cmds:
      - rm -rf dist/
