// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function GetFEN():Promise<string>;

export function GetMoves():Promise<Array<engine.Move>>;

export function GetPieces():Promise<Record<number, string>>;

export function IsCheckmate():Promise<boolean>;

export function IsFiftyMoveRule():Promise<boolean>;

export function IsInCheck():Promise<boolean>;

export function IsInsufficientMaterial():Promise<boolean>;

export function IsStalemate():Promise<boolean>;

export function IsThreefoldRepetition():Promise<boolean>;

export function NewGame():Promise<void>;

export function PlayMove(arg1:engine.Move):Promise<engine.Undo>;

export function UndoMove(arg1:engine.Move,arg2:engine.Undo):Promise<void>;
