// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFEN() {
  return window['go']['main']['App']['GetFEN']();
}

export function GetMoves() {
  return window['go']['main']['App']['GetMoves']();
}

export function GetPieces() {
  return window['go']['main']['App']['GetPieces']();
}

export function IsCheckmate() {
  return window['go']['main']['App']['IsCheckmate']();
}

export function IsDraw() {
  return window['go']['main']['App']['IsDraw']();
}

export function IsFiftyMoveRule() {
  return window['go']['main']['App']['IsFiftyMoveRule']();
}

export function IsInCheck() {
  return window['go']['main']['App']['IsInCheck']();
}

export function IsInsufficientMaterial() {
  return window['go']['main']['App']['IsInsufficientMaterial']();
}

export function IsStalemate() {
  return window['go']['main']['App']['IsStalemate']();
}

export function IsThreefoldRepetition() {
  return window['go']['main']['App']['IsThreefoldRepetition']();
}

export function PlayMove(arg1) {
  return window['go']['main']['App']['PlayMove'](arg1);
}

export function UndoMove(arg1, arg2) {
  return window['go']['main']['App']['UndoMove'](arg1, arg2);
}
